Demo/analyzer (#260)
* Initial commit

* Add file upload handling

* Improve mic and other buttons

* Improve panel scroll behaviour

* Implement file upload

* Add audio player

* Handle invalid file mime types on drag

* Fix ui not updating after classification was done

* Fix segment status layout issue

* Use h5 audio player

* Make player a bit lower

* Update share image

* Disable tap highlight color

* Fix player promise error and add disabled styles

* Truncate overflowing sidebar item texts

* Make player stick to bottom

* Minor tweaks

* Player visual tweaks

* Improve details rendering

* Clear segments on source change, improve logging and don't allow changing source while decoder is active

* Add samples audios

* Add homepage property to package.json

* Delete package-lock.json.bak

* Remove placeholder content

* Use different appid

* Setup deployment action

* Update demo deploy actions

* Update dependencies to make `rush build` pass

There was a `error TS2300: Duplicate identifier 'LibraryManagedAttributes` apparently caused by @types/react version 18.0.25 and 18.0.26 conflict. Updated react-ui styled-component and @types/styled-components to latest minor version which seemed to mitigate the issue.

* Use staging version of classifier api

* Add validation for adding tags

* Fix sidebar and remove logging

* Style tweaks

* Update UI

* Display audio events using mock data

* Update empty state styles

* Style changes

* Fix spinner width

* Refactor classify api response handling

* Add audio event detection

* WIP: use own browser microphone

* periodically call audio classifier

* Update mic button and remove logging

* Remove counter

* Fix promise error in chrome

Before this change i got this error below when selecting a sample file: Uncaught (in promise) DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Cannot decode detached ArrayBuffer

* Remove react-ui dependency

As we're using our own BrowserMicrophone, the IntroPopup is never shown

* Actually fix chrome promise error

* Refactor code and display audio classifications at the bottom

* Clear segments when using microphone

* Record and store microphone audio

* Fix uncaught promise in classifyBuffer

* Refactor mic buffer implementation

* fix audiobuffer copying

* Replace h5 audio player with wavesurfer 🏄‍♂️

* Fix audio events per chunk

* UI improvements

* Fix player volume/play

* merge

* Fix corner cases, move mic button to bottom and tweak styles

* Enable playing recent recording

* Show timestamps and timeline and style tweaks

* Only show empty state on first use

* Fix mic button for Safari

* Fix timeline colors

* Play from region start when clicking region

* Fix timeline jumping

* Rush change

* Use prod API endpoints

* Add tap-to-talk

* Stronger region hover

* Don't show text classification if no tags

* Update empty state title

* Format

* use endTimestamp to determine segment start time

* Update default labels

* Update text labels

* Add auto scroll

Co-authored-by: Juho Kilpikoski <juho@speechly.com>
Co-authored-by: Antti Ukkonen <antti@speechly.com>