Update dependencies to make `rush build` pass
There was a `error TS2300: Duplicate identifier 'LibraryManagedAttributes` apparently caused by @types/react version 18.0.25 and 18.0.26 conflict. Updated react-ui styled-component and @types/styled-components to latest minor version which seemed to mitigate the issue.